package datatypes

import (
	"errors"
	"strings"

	log "github.com/Sirupsen/logrus"
)

var (
	ErrInvalidClass        = errors.New("invalid class")
	ErrInvalidOddParameter = errors.New("parameter count must be even")
)

const (
	CommandI int = iota + 1
	ActorI
	ObjectI
	TimeI
	PlaceI
	NoneI
)

const (
	FlexIdTypeEmail int = iota + 1
	FlexIdTypePhone
)

var String map[int]string = map[int]string{
	CommandI: "Command",
	ActorI:   "Actor",
	ObjectI:  "Object",
	TimeI:    "Time",
	PlaceI:   "Place",
	NoneI:    "None",
}

var Pronouns map[string]int = map[string]int{
	"me":    ActorI,
	"us":    ActorI,
	"you":   ActorI,
	"him":   ActorI,
	"her":   ActorI,
	"them":  ActorI,
	"it":    ObjectI,
	"that":  ObjectI,
	"there": PlaceI,
	"then":  TimeI,
}

// StructuredInput is generated by Ava and sent to packages. The UserId is
// guaranteed to be unique. The FlexId is used for UserId lookups to maintain
// context, such as a phone number or email address.
type StructuredInput struct {
	UserId     int
	FlexId     string
	FlexIdType int
	// TODO: Check if authenticated. If not, packages may require
	// authentication
	Sentence string
	Commands []string
	Actors   []string
	Objects  []string
	Times    []string
	Places   []string
}

func (si *StructuredInput) String() string {
	s := "\n"
	if len(si.Commands) > 0 {
		s += "Command: " + strings.Join(si.Commands, ", ") + "\n"
	}
	if len(si.Actors) > 0 {
		s += "Actors: " + strings.Join(si.Actors, ", ") + "\n"
	}
	if len(si.Objects) > 0 {
		s += "Objects: " + strings.Join(si.Objects, ", ") + "\n"
	}
	if len(si.Times) > 0 {
		s += "Times: " + strings.Join(si.Times, ", ") + "\n"
	}
	if len(si.Places) > 0 {
		s += "Places: " + strings.Join(si.Places, ", ") + "\n"
	}
	return s[:len(s)-1] + "\n"
}

type WordClass struct {
	Word  string
	Class int
}

// Add pairs of words with their classes to a structured input. Params should
// follow the ("Order", "Command"), ("noon", "Time") form.
func (si *StructuredInput) Add(wc []WordClass) error {
	if len(wc) == 0 {
		return ErrInvalidOddParameter
	}
	for _, w := range wc {
		switch w.Class {
		case CommandI:
			si.Commands = append(si.Commands, w.Word)
		case ActorI:
			si.Actors = append(si.Actors, w.Word)
		case ObjectI:
			si.Objects = append(si.Objects, w.Word)
		case TimeI:
			si.Times = append(si.Times, w.Word)
		case PlaceI:
			si.Places = append(si.Places, w.Word)
		case NoneI:
			// Do nothing
		default:
			log.Error("invalid class: ", w.Class)
			return ErrInvalidClass
		}
	}
	return nil
}

// TODO Optimize by passing back a struct with []string AND int (ActorI,
// ObjectI, etc.)
func (si *StructuredInput) Pronouns() []string {
	p := []string{}
	for _, w := range si.Objects {
		if Pronouns[w] != 0 {
			p = append(p, w)
		}
	}
	for _, w := range si.Actors {
		if Pronouns[w] != 0 {
			p = append(p, w)
		}
	}
	for _, w := range si.Times {
		if Pronouns[w] != 0 {
			p = append(p, w)
		}
	}
	for _, w := range si.Places {
		if Pronouns[w] != 0 {
			p = append(p, w)
		}
	}
	return p
}
