CREATE TABLE responses (
	id SERIAL,
	userid INTEGER NOT NULL,
	inputid INTEGER NOT NULL,
	sentence VARCHAR(255) NOT NULL,
	route VARCHAR(255) NOT NULL,
	stateid INTEGER,
	feedbackid INTEGER,
	createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (id)
);
ALTER TABLE messages RENAME TO inputs;
ALTER TABLE inputs DROP COLUMN avasent;
ALTER TABLE inputs ADD COLUMN responseid INTEGER NOT NULL DEFAULT 0;
ALTER TABLE inputs ADD COLUMN commands VARCHAR(255) ARRAY;
ALTER TABLE inputs ADD COLUMN objects VARCHAR(255) ARRAY;
ALTER TABLE inputs ADD COLUMN actors VARCHAR(255) ARRAY;
ALTER TABLE inputs ADD COLUMN times VARCHAR(255) ARRAY;
ALTER TABLE inputs ADD COLUMN places VARCHAR(255) ARRAY;
ALTER TABLE inputs ADD COLUMN flexid VARCHAR(255);
ALTER TABLE inputs ADD COLUMN flexidtype INTEGER;
