ALTER TABLE trainings RENAME COLUMN trainedcount TO trained;
ALTER TABLE trainings ALTER COLUMN trained SET DEFAULT NULL;
ALTER TABLE trainings ALTER COLUMN trained TYPE BOOLEAN USING
	CASE
		WHEN trained=0 THEN FALSE ELSE TRUE
	END;
ALTER TABLE trainings ALTER COLUMN trained SET DEFAULT FALSE;
