CREATE TABLE IF NOT EXISTS users (
	id SERIAL,
	email VARCHAR(255) UNIQUE NOT NULL,
	createdat DATE DEFAULT CURRENT_TIMESTAMP,
	updatedat DATE DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS inputs (
	id SERIAL,
	userid INTEGER,
	flexid VARCHAR(255),
	flexidtype INTEGER,
	commands VARCHAR(255) ARRAY,
	objects VARCHAR(255) ARRAY,
	actors VARCHAR(255) ARRAY,
	times VARCHAR(255) ARRAY,
	places VARCHAR(255) ARRAY,
	response VARCHAR(255),
	package VARCHAR(255),
	createdat DATE DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);
