CREATE TABLE scheduledevents (
	id SERIAL,
	content VARCHAR(255) NOT NULL,
	flexid VARCHAR(255) NOT NULL,
	flexidtype INTEGER NOT NULL,
	sendat TIMESTAMP NOT NULL,
	sent BOOLEAN NOT NULL DEFAULT FALSE,
	createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (id)
);
