CREATE TABLE preferences (
	id SERIAL,
	key VARCHAR(255) NOT NULL,
	value VARCHAR(255) NOT NULL,
	pkgname VARCHAR(255),
	userid INTEGER NOT NULL,
	createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (id)
);
