ALTER TABLE trainings ALTER COLUMN trained SET DEFAULT NULL;
ALTER TABLE trainings ALTER COLUMN trained TYPE INTEGER USING
	CASE
		WHEN trained=FALSE THEN 0 ELSE 3
	END;
ALTER TABLE trainings ALTER COLUMN trained SET DEFAULT 0;
ALTER TABLE trainings RENAME COLUMN trained TO trainedcount;
