CREATE TABLE cards (
	id SERIAL,
	userid INTEGER NOT NULL,
	addressid INTEGER NOT NULL DEFAULT 0,
	last4 VARCHAR(4) NOT NULL,
	cardholdername VARCHAR(255) NOT NULL,
	expmonth INTEGER NOT NULL,
	expyear INTEGER NOT NULL,
	brand VARCHAR(20) NOT NULL,
	stripeid VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY (id)
);
ALTER TABLE users ADD COLUMN stripecustomerid VARCHAR(255) NOT NULL DEFAULT '';
