CREATE TABLE cards (
	userid INTEGER NOT NULL,
	stripeid VARCHAR(255) NOT NULL,
	last4 VARCHAR(4) NOT NULL,
	name VARCHAR(255) NOT NULL,
	expmonth INTEGER NOT NULL,
	expyear INTEGER NOT NULL,
	addressline1 VARCHAR(255) NOT NULL,
	addressline2 VARCHAR(255) NOT NULL,
	city VARCHAR(255) NOT NULL,
	state VARCHAR(255) NOT NULL,
	country VARCHAR(2) NOT NULL,
	zip VARCHAR(20) NOT NULL,
	brand VARCHAR(20) NOT NULL,
	fingerprint VARCHAR(255) NOT NULL,
	PRIMARY KEY (stripeid)
);
ALTER TABLE users ADD COLUMN stripeid VARCHAR(255) DEFAULT '' NOT NULL;
